### ISSUE TITLE
Codepoint vs. character

### ISSUE THREAD

**Issue by joewiz** [lcahlander/miscXQuery#1]
Cool project, Loren! The nice thing about declaring each of these as global variables is that a code-completion-capable IDE could suggest the available values. Other approaches, such as putting all values in an XML document for lookup with XPath or an XQuery 3.0 map for lookup with the lookup operator, wouldn't provide this.

But the issue I was going to write about was this:

I think the "code point" column should be renamed "character", since the code point (as evidenced by the return values of the `fn:string-to-codepoints()` function) is a decimal value, sans the `&#` prefix and `;` suffix. Having two columns could be quite useful, actually: "character" (with `&#__;`) and "code point" (with just the decimal).

A minor point: some of the entries in the description column still have footnotes that should probably be stripped, e.g., `[d]` in `no-break space (non-breaking space)[d]`.

**Comment by lcahlander** [comment]
Fixed

**Comment by lcahlander** [comment]
removed the footnote marks

**Comment by lcahlander** [comment]
I will probably create a separate XQuery 3.0 map file.  I already created a java file with the mapping.

**Comment by joewiz** [comment]
Having multiple editions could make for an interesting comparison of the pros and cons of storing and querying data in different data structures with XQuery.

**Comment by lcahlander** [comment]
Added an XML variable to be able to lookup encodings:

&lt;foo&gt;{$encchars:encoding//encoding[@name = "Acirc"]}&lt;/foo&gt;

Keeping it as XQuery version 1.0 for useability.

**Comment by joewiz** [comment]
Nice :-)

**Comment by lcahlander** [comment]
It is also in the gist [https://gist.github.com/lcahlander/b040744256b81f881c583169e4f7b4d0](https://gist.github.com/lcahlander/b040744256b81f881c583169e4f7b4d0)

**Comment by dmccreary** [comment]
Thanks for the feedback Joe!  Good to see you are still in the XQuery world!
